//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreePDFPasswordRemover {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResTranslate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTranslate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreePDFPasswordRemover.ResTranslate", typeof(ResTranslate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version has been released. Press the OK button to download the new version.
        /// </summary>
        internal static string A_new_version_has_been_released__Press_the_OK_button_to_download_the_new_version {
            get {
                return ResourceManager.GetString("A new version has been released. Press the OK button to download the new version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version has been released. Would you like to download it now ?.
        /// </summary>
        internal static string A_new_version_has_been_released__Would_you_like_to_download_it_now__ {
            get {
                return ResourceManager.GetString("A new version has been released. Would you like to download it now ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured !.
        /// </summary>
        internal static string An_error_occured__ {
            get {
                return ResourceManager.GetString("An error occured !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while removing Passwords from PDF File.
        /// </summary>
        internal static string An_error_occured_while_removing_Passwords_from_PDF_File {
            get {
                return ResourceManager.GetString("An error occured while removing Passwords from PDF File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download new version ?.
        /// </summary>
        internal static string Download_new_version__ {
            get {
                return ResourceManager.GetString("Download new version ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt PDF.
        /// </summary>
        internal static string Encrypt_PDF {
            get {
                return ResourceManager.GetString("Encrypt PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not Create Directory for File.
        /// </summary>
        internal static string Error__Could_not_Create_Directory_for_File {
            get {
                return ResourceManager.GetString("Error. Could not Create Directory for File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not send Questionnaire !.
        /// </summary>
        internal static string Error__Could_not_send_Questionnaire__ {
            get {
                return ResourceManager.GetString("Error. Could not send Questionnaire !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Wrong User Password for File.
        /// </summary>
        internal static string Error__Wrong_User_Password_for_File {
            get {
                return ResourceManager.GetString("Error. Wrong User Password for File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Could not change Language !.
        /// </summary>
        internal static string Error_Could_not_change_Language__ {
            get {
                return ResourceManager.GetString("Error Could not change Language !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not parse Arguments !.
        /// </summary>
        internal static string Error_could_not_parse_Arguments__ {
            get {
                return ResourceManager.GetString("Error could not parse Arguments !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great free tool for Removing Passwords from PDF Documents !.
        /// </summary>
        internal static string Great_free_tool_for_Removing_Passwords_from_PDF_Documents__ {
            get {
                return ResourceManager.GetString("Great free tool for Removing Passwords from PDF Documents !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is From Windows Explorer.
        /// </summary>
        internal static string Is_From_Windows_Explorer {
            get {
                return ResourceManager.GetString("Is From Windows Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Cancelled !.
        /// </summary>
        internal static string Operation_Cancelled__ {
            get {
                return ResourceManager.GetString("Operation Cancelled !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully !.
        /// </summary>
        internal static string Operation_completed_successfully__ {
            get {
                return ResourceManager.GetString("Operation completed successfully !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed with Errors !.
        /// </summary>
        internal static string Operation_completed_with_Errors__ {
            get {
                return ResourceManager.GetString("Operation completed with Errors !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite PDF Document.
        /// </summary>
        internal static string Overwrite_PDF_Document {
            get {
                return ResourceManager.GetString("Overwrite PDF Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a PDF File first !.
        /// </summary>
        internal static string Please_add_a_PDF_File_first__ {
            get {
                return ResourceManager.GetString("Please add a PDF File first !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add only PDF Files !.
        /// </summary>
        internal static string Please_add_only_PDF_Files__ {
            get {
                return ResourceManager.GetString("Please add only PDF Files !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add PDF Files first !.
        /// </summary>
        internal static string Please_add_PDF_Files_first__ {
            get {
                return ResourceManager.GetString("Please add PDF Files first !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Subfolder Name !.
        /// </summary>
        internal static string Please_enter_a_Subfolder_Name__ {
            get {
                return ResourceManager.GetString("Please enter a Subfolder Name !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Subfolder Name !.
        /// </summary>
        internal static string Please_enter_a_valid_Subfolder_Name__ {
            get {
                return ResourceManager.GetString("Please enter a valid Subfolder Name !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the correct User Password !.
        /// </summary>
        internal static string Please_enter_the_correct_User_Password__ {
            get {
                return ResourceManager.GetString("Please enter the correct User Password !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the Questionnaire !.
        /// </summary>
        internal static string Please_fill_out_the_Questionnaire__ {
            get {
                return ResourceManager.GetString("Please fill out the Questionnaire !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a valid Password !.
        /// </summary>
        internal static string Please_insert_a_valid_Password__ {
            get {
                return ResourceManager.GetString("Please insert a valid Password !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify another option as the Output Folder !.
        /// </summary>
        internal static string Please_specify_another_option_as_the_Output_Folder__ {
            get {
                return ResourceManager.GetString("Please specify another option as the Output Folder !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove PDF Password.
        /// </summary>
        internal static string Remove_PDF_Password {
            get {
                return ResourceManager.GetString("Remove PDF Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Folder of PDF Document.
        /// </summary>
        internal static string Same_Folder_of_PDF_Document {
            get {
                return ResourceManager.GetString("Same Folder of PDF Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolder.
        /// </summary>
        internal static string Subfolder {
            get {
                return ResourceManager.GetString("Subfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolder of PDF Document.
        /// </summary>
        internal static string Subfolder_of_PDF_Document {
            get {
                return ResourceManager.GetString("Subfolder of PDF Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the latest version !.
        /// </summary>
        internal static string This_is_the_latest_version__ {
            get {
                return ResourceManager.GetString("This is the latest version !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified Error.
        /// </summary>
        internal static string Unspecified_Error {
            get {
                return ResourceManager.GetString("Unspecified Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to add also Subdirectories ?.
        /// </summary>
        internal static string Would_you_like_to_add_also_Subdirectories__ {
            get {
                return ResourceManager.GetString("Would you like to add also Subdirectories ?", resourceCulture);
            }
        }
    }
}
